name: Setup Analytics env
description: Setup build env for analytics backend
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install poetry
      shell: bash
    - run: poetry install
      shell: bash
      working-directory: analytics
      env:
        POETRY_VIRTUALENVS_IN_PROJECT: true
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-py3.10-venv-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-py3.10-venv-
